version: "3"
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11"
        POETRY_VERSION: "1.5.1"
    volumes:
      - .:/workspace
    ports:
      - 8888:8888
    tty: true
    env_file:
      - ./.env