version: '3.8'
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.11"
        POETRY_VERSION: "1.5.1"
    volumes:
      - .:/workspace
      - /workspace/.venv
    ports:
      - 8888:8888
    tty: true
    env_file:
      - ./.env
    environment: 
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]